# HW 2
## 32140704 김성환

ch2

In [8]:
print('Q 2.2\n')

mylist2=['python','is','fun']
print(mylist2,'\n')
print(f'mylist2 = {mylist2[0]},{mylist2[1]},{mylist2[2]}')

Q 2.2

['python', 'is', 'fun'] 

mylist2 = python,is,fun


In [9]:
print('Q 2.4\n')
import numpy as np

a=np.array([1,2,3,4,5])
print('a = ',a)

Q 2.4

a =  [1 2 3 4 5]


In [11]:
print('Q 2.6\n')
import numpy as np

a=np.array([1,2,3,4,5])
b=np.array([91,92,93,94,95])
c=a+b
d=a-b

print('c = a + b = ',c)
print('d = a - b = ',d)

Q 2.6

c = a + b =  [ 92  94  96  98 100]
d = a - b =  [-90 -90 -90 -90 -90]


In [15]:
print('Q 2.8\n')
import numpy as np

B=np.array([[1,2,99],
            [3,4,100],
            [5,6,101]])
print('B =\n',B)

Q 2.8

B =
 [[  1   2  99]
 [  3   4 100]
 [  5   6 101]]


행렬의 형태가 깨져서 나오는 것은 어쩔 수가 없어, Pandas 같은 다른 라이브러리의 호출이 필요한 것으로 추측된다.

In [20]:
print('Q 2.10\n')
import numpy as np
import random

num1=random.randrange(1,151)
num2=random.randrange(1,151)
num3=random.randrange(1,151)
num=np.array([num1,num2,num3])

for i in range(len(num)):
    if num[i] >=90:
        print('score =',num[i],'grade = A')
    else:
        print('score =',num[i],'grade = B')

Q 2.10

score = 82 grade = B
score = 87 grade = B
score = 129 grade = A


In [28]:
print('Q 2.10\n')
import numpy as np
import random

num1=random.randrange(1,151)
num2=random.randrange(1,151)
num3=random.randrange(1,151)
num=np.array([num1,num2,num3])

for i in range(len(num)):
    if num[i] >=90:
        print('score =',num[i],'grade = A')
    elif num[i] >=80:
        print('score =',num[i],'grade = B')
    else:
        print('score =',num[i],'grade = C')

Q 2.10

score = 76 grade = C
score = 135 grade = A
score = 83 grade = B


ch3

## 수치해석 보고서
### 목적: 수치해석에 대한 내용을 Markdown으로 정리한다.

#### 수치해석의 기본 과정
1. 알고리즘에 대한 이해
2. 프로그램 작성
3. 프로그램 실행 및 검증

#### 예제: 다음에 주어진 방정식의 해를 구하시오.
> $x e^{-x} + 1 = 0$

다음은 반복적인 과정을 반복하여 문제를 해결하는 방법이다.
>\begin{equation}
    x^{(k+!)}+i = x^{(k)}_i - \frac{5x^{(k)} - 3}{5}
\end{equation}

#### 예제: 다음에 주어진 연립 방정식의 해를 구하시오.
>Ax = b, 

여기서

>\begin{equation}
    A = \begin{bmatrix}
            1 & 2 \\
            3 & 4
        \end{bmatrix},
    B = \begin{pmatrix}
            99 \\ 100
        \end{pmatrix}
\end{equation}

연립 방정식의 해는 다음과 같이 계산할 수 있다.

>\begin{equation}
    x = A^{-1}b
\end{equation}

따라서,

>\begin{equation}
    x = \begin{bmatrix}
            1 & 2 \\
            3 & 4
        \end{bmatrix}^{-1}
    \begin{pmatrix}
        99 \\
        100
    \end{pmatrix}
\end{equation}

#### 결론: Markdown으로 작성한 수치해석 보고서를 제출합니다.

(예제 1 : 뉴턴해법이라고도 생각되지 않고 무슨 해법인지 알 수가 없습니다.)

식 뒤에 문자를 넣는 것보다 문자를 따로 빼고 식만 작성하는 것이 더 이해하기 깔끔해서 그렇게 하였습니다.

>\begin{equation}
    x = \frac{1}{1\times4 - 2\times3}
    \begin{bmatrix}
        4 & -2 \\
        -3 & 1
    \end{bmatrix}
    \times
    \begin{pmatrix}
        99 \\
        100
    \end{pmatrix}
\end{equation}

#### Q 3.2
Python is *fun* to learn

**Python** is a great computer language

#### Q 3.4
>\begin{equation}
    \sqrt{2}=1.414
\end{equation}

>\begin{equation}
    \frac{a}{b}=3.14
\end{equation}

#### Q 3.6
>\begin{equation}
    x^{(k+1)}_j = 0.4x^{(k)}_j + 1.1
\end{equation}

#### Q 3.8
>\begin{equation}
    \sum_{i=0}^{n}a_i = a_1 + a_2 + ...
\end{equation}

#### Q 3.10
>\begin{equation}
    \sum_{i=0}^{n} (y_i - b - ax_i)^{2}
\end{equation}

#### Q 3.12
>\begin{equation}
    \frac{dy}{dt} = -xe^{x} + 3
\end{equation}

모든 예제에 나오는 기능함수를 다 작성해보았습니다.