# jacobi

동일한 행렬 사용

In [23]:
import numpy as np

A=np.array([[2,1,0],
            [1,4,-1],
            [0,-1,7]])
b=np.array([4,6,19])

In [24]:
import numpy as np
N=10
xo=np.zeros((len(b),1))
# 초기값 영벡터로 통일, b주는 값에 맞게

L=np.tril(A,-1)
U=np.triu(A,1)
D=np.diag(np.diag(A)) #그냥 하면 벡터로 > 이중으로 해야 행렬

invD=np.linalg.inv(D)
former=invD@b

for k in range(N):
    latter= -(invD@(L+U))@xo
    xnew=former+latter
    xo=xnew
    print('N = ',k+1)
    np.set_printoptions(precision=3)
    print(xnew,'\n')

N =  1
[[2.    1.5   2.714]
 [2.    1.5   2.714]
 [2.    1.5   2.714]] 

N =  2
[[1.    0.75  1.357]
 [2.    1.5   2.714]
 [2.286 1.714 3.102]] 

N =  3
[[1.    0.75  1.357]
 [2.321 1.741 3.151]
 [2.286 1.714 3.102]] 

N =  4
[[0.839 0.629 1.139]
 [2.321 1.741 3.151]
 [2.332 1.749 3.164]] 

N =  5
[[0.839 0.629 1.139]
 [2.373 1.78  3.221]
 [2.332 1.749 3.164]] 

N =  6
[[0.813 0.61  1.104]
 [2.373 1.78  3.221]
 [2.339 1.754 3.174]] 

N =  7
[[0.813 0.61  1.104]
 [2.381 1.786 3.232]
 [2.339 1.754 3.174]] 

N =  8
[[0.809 0.607 1.098]
 [2.381 1.786 3.232]
 [2.34  1.755 3.176]] 

N =  9
[[0.809 0.607 1.098]
 [2.383 1.787 3.234]
 [2.34  1.755 3.176]] 

N =  10
[[0.809 0.606 1.097]
 [2.383 1.787 3.234]
 [2.34  1.755 3.176]] 



책과의 결과가 다르게 나오는 부분

## Gauss-Seidel

In [25]:
N=10
xo=np.zeros((len(b),1))

L=np.tril(A,-1)
U=np.triu(A,1)
D=np.diag(np.diag(A))

invLD=np.linalg.inv(L+D)
former=invLD

for k in range(N):
    latter=b-U@xo
    xnew=former@latter
    xo=xnew
    print('N = ',k+1)
    np.set_printoptions(precision=3)
    print(xnew)

N =  1
[[2.    3.    9.5  ]
 [0.5   0.75  2.375]
 [0.643 0.964 3.054]]
N =  2
[[1.75  2.625 8.312]
 [0.723 1.085 3.435]
 [0.675 1.012 3.205]]
N =  3
[[1.638 2.458 7.782]
 [0.759 1.139 3.606]
 [0.68  1.02  3.229]]
N =  4
[[1.62  2.431 7.697]
 [0.765 1.147 3.633]
 [0.681 1.021 3.233]]
N =  5
[[1.618 2.426 7.683]
 [0.766 1.149 3.637]
 [0.681 1.021 3.234]]
N =  6
[[1.617 2.426 7.681]
 [0.766 1.149 3.638]
 [0.681 1.021 3.234]]
N =  7
[[1.617 2.426 7.681]
 [0.766 1.149 3.638]
 [0.681 1.021 3.234]]
N =  8
[[1.617 2.426 7.681]
 [0.766 1.149 3.638]
 [0.681 1.021 3.234]]
N =  9
[[1.617 2.426 7.681]
 [0.766 1.149 3.638]
 [0.681 1.021 3.234]]
N =  10
[[1.617 2.426 7.681]
 [0.766 1.149 3.638]
 [0.681 1.021 3.234]]
